name: application

services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./.docker/nginx/Dockerfile
    volumes:
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php-fpm
    ports:
      - "8080:80"
    networks:
      - internal
  php-fpm:
    container_name: php-fpm
    build:
      context: .
      dockerfile: ./.docker/php-fpm/Dockerfile
    volumes:
      - ./public:/var/www/public:ro
      - ./src:/var/www/src:ro
      - ./composer.json:/var/www/composer.json:ro
      - ./composer.lock:/var/www/composer.lock:ro
    networks:
      - internal

networks:
  internal:
    driver: bridge
