version: '3'

services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./.docker/nginx/Dockerfile
    volumes:
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public:/var/www/public:rw
    depends_on:
      - php-fpm
    ports:
      - "8080:80"
    networks:
      - internal
  php-fpm:
    container_name: php-fpm
    build:
      context: .
      dockerfile: ./.docker/php-fpm/Dockerfile
    volumes:
      - ./public:/var/www/public:rw
      - ./src:/var/www/src:rw
      - ./composer.json:/var/www/composer.json:ro
      - ./composer.lock:/var/www/composer.lock:ro
    ports:
      - "9000:9000"
    networks:
      - internal
    devices:
      - /dev/ttyACM0:/dev/ttyACM0

networks:
  internal:
    driver: bridge
